# Generated by Django 5.2.5 on 2025-09-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='link',
            new_name='website',
        ),
    ]
